version: "3"

services:
  app_1:
    build: .
    ports:
      - "3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=app_user
      - DATABASE_PASSWORD=app_password
      - REDIS_HOST=redis
      - NODE_ID=1
    depends_on:
      - db
      - redis

  app_2:
    extends: app_1
    environment:
      - NODE_ID=2

  db:
    image: docker.io/postgres:latest
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password

  redis:
    image: docker.io/redis:latest

  load_balancer1:
    image: docker.io/nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_1
      - app_2

  load_balancer2:
    image: docker.io/haproxy:latest
    ports:
      - "8082:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - app_1
      - app_2
